#spring:
#  profiles:
#    active: dev
#  datasource:
#    druid:
#      ##########JDBC 配置 #######################
#      url: jdbc:mysql://www.yilaiyiwang.com:3306/pra?characterEncoding=utf-8
#      username: yilaiyiwang
#      password: ylyw20170930
#      driver-class-name: com.mysql.jdbc.Driver
#      ##########连接池配置#######################
##      initial-size: 20
##      max-active: 50
##      min-idle:
##      max-wait:
##      pool-prepared-statements:
##      max-pool-prepared-statement-per-connection-size:
##      max-open-prepared-statements:            #和上面的等价
##      validation-query:
##      validation-query-timeout:
##      test-on-borrow:
##      test-on-return:
##      test-while-idle:
##      time-between-eviction-runs-millis:
##      min-evictable-idle-time-millis:
##      max-evictable-idle-time-millis:
##      filters:            #配置多个英文逗号分隔
##      ##########监控配置#######################
##      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
##      web-stat-filter:
##        enabled:  #是否启用StatFilter默认值true
##        url-pattern:
##        exclusions:
##        session-stat-enable:
##        session-stat-max-count:
##        principal-session-name:
##        principal-cookie-name:
##        profile-enable:
##      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
##      druid.stat-view-servlet:
##        enabled:  #是否启用StatViewServlet默认值true
##        url-pattern:
##        reset-enable:
##        login-username:
##        login-password:
##        allow:
##        deny:
##      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
##      aop-patterns:  # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#
#  cloud:
#    discovery:
#      enabled: true
#      serviceId: eureka-server
#  redis:
#  #################redis基础配置#################
#    database: 8
##    host: 192.168.0.63
#    host: 127.0.0.1
#    password:
#    port: 6379
#    timeout: 5000
#  #################redis线程池设置#################
#    jedis:
#      pool:
#        max-idle: 500
#        min-idle: 50
#        max-active: 2000
#        max-wait: 1000
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://localhost:8888/eureka/
#
#feign:
#  hystrix:
#    enabled: true
#
## mybatis
#mybatis:
#  mapper-locations:  classpath:mapping/*/*.xml
#  type-aliases-package: com.prostate.*.entity
#
#
